### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by abbids** [dustinmoris/DustedCodes#13]
It might be under a wrong heading (apologize for that), 
1. do you have a workable example of what you explained in (https://dusted.codes/demystifying-aspnet-mvc-5-error-pages-and-error-logging).
2. does ELMAH covers all of this industry standard best practices?

**Comment by dustinmoris** [comment]
Hi, no unfortunately I don't have an example with all those examples, but yes, I'd recommend to use ELMAH in your application which is an ASP.NET module and will capture all application wide errors and log them for you. It also offers you an endpoint which you can configure to easily read the error logs.

In terms of error pages you can have a look how I implemented them and I would consider that as a best practise:
https://github.com/dustinmoris/DustedCodes/blob/master/DustedCodes.Blog/Web.config#L59-L68

and the error pages are located here: https://github.com/dustinmoris/DustedCodes/tree/master/DustedCodes.Blog/Assets/ErrorPages
